title: Labs
description: ğŸ‘¨â€ğŸ« Courses and projects
baseurl: "/labs"
url: "https://khannurien.github.io"

heading_anchors: true

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
